library(dslabs)
data(gapminder)
head(gapminder)
library(ggplot2)
library(tidyverse)
filter(gapminder, year %in% c(1962,1970,1980,1990,2000,2012)) %>% ggplot(aes(life_expectancy, fertility, color=continent)) + geom_point() + facet_wrap(~year)
filter(gapminder, country %in% c("South Korea", "Germany")) %>% ggplot(aes(year, fertility, col=country)) + geom_line()
countries = c("South Korea","Germany")
labels <- data.frame(country = countries, x = c(1975, 1965), y = c(60, 72))
filter(gapminder, country %in% countries) %>% ggplot(aes(year, life_expectancy, col=country)) + geom_line() + geom_text(data=labels,aes(x,y,label=country)) + theme(legend.position="none")
