library(dslabs)
library(png)
library(transformr)
library(ggplot2)
library(gganimate)
library(tidyverse)
library(ggthemes)
data(gapminder)
head(gapminder)
newdata <- select(gapminder,country,year,life_expectancy,population,gdp,continent)
newdata <- filter(newdata,continent %in% c("Africa","Europe","Asia") & year %in% c("1972","1982","1997","2010"))
newdata <- mutate(newdata,gdpPerCapita=gdp/population)
head(newdata)
p1 <- boxplot(life_expectancy~continent,newdata)
newdata$life_expectancy[newdata$life_expectancy>75 & newdata$continent=="Africa"] <- median(newdata$life_expectancy)
p2 <- boxplot(life_expectancy~continent,newdata)
newdata$life_expectancy[newdata$life_expectancy<53 & newdata$continent=="Asia"] <- median(newdata$life_expectancy)
p3 <- boxplot(life_expectancy~continent,newdata)
p4 <- ggplot(newdata,aes(gdpPerCapita,life_expectancy, col = continent,size=population/1.0e+06)) + geom_point(shape=16) + facet_grid(continent ~ year) + labs(title="GDP Per Capita vs Life Expectancy (1962 - 2010)",x="GDP Per Capita",y="Life Expectancy",col="Continent",size="Population") + scale_x_continuous(breaks=seq(0,60000,15000),limits=c(0,60000))
library(ggthemes)
p4 + theme_igray()
p4
