library(readxl)
data <- read_excel("S:\\R\\DS Home Assg\\GDP.xls",sheet=1)
head(data)
library(dplyr)
newdata <- select(data,CountryName,"1970","1980","1990","2000","2010","2018")
head(newdata)
naprop <- colSums(is.na(newdata))/nrow(newdata)
round(naprop,2)
library(ggplot2)
newdata %>% ggplot(aes(y=CountryName)) + geom_line()
